name: trelltech
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  oauth1: ^2.0.0
  go_router: ^13.2.0
  provider: ^6.1.2
  webview_flutter: ^4.7.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BungeeShade
      fonts:
        - asset: fonts/BungeeShade-Regular.ttf
          weight: 400
    - family: LexendExa
      fonts:
        - asset: fonts/LexendExa-Regular.ttf
        - asset: fonts/LexendExa-Black.ttf
          weight: 900
        - asset: fonts/LexendExa-Bold.ttf
          weight: 700
        - asset: fonts/LexendExa-ExtraBold.ttf
          weight: 800
        - asset: fonts/LexendExa-ExtraLight.ttf
          weight: 200
        - asset: fonts/LexendExa-Light.ttf
          weight: 300
        - asset: fonts/LexendExa-Medium.ttf
          weight: 500
        - asset: fonts/LexendExa-SemiBold.ttf
          weight: 600
        - asset: fonts/LexendExa-Thin.ttf
          weight: 100
        - asset: fonts/LexendExa-VariableFont_wght.ttf
          weight: 400
